### ISSUE TITLE
cmake build failed

### ISSUE THREAD

**Issue by Travis990** [dchapyshev/aspia#108]
![image](https://user-images.githubusercontent.com/6883210/119826993-39411e80-bf2b-11eb-8392-95419f5c2104.png)

**Comment by Travis990** [comment]
5.14 is ok

**Comment by libaineu2004** [comment]
I ran into the same problem:

CMake Error at source/client/CMakeLists.txt:244 (qt5_import_plugins):
Unknown CMake command "qt5_import_plugins".


Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/Desktop/aspia-master/x86/CMakeFiles/CMakeOutput.log".

**Comment by libaineu2004** [comment]
I ran into the same problem:

CMake Error at source/client/CMakeLists.txt:244 (qt5_import_plugins):
Unknown CMake command "qt5_import_plugins".


Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/Desktop/aspia-master/x86/CMakeFiles/CMakeOutput.log".
