### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by PejmanNik** [dchapyshev/aspia#11]
Hello. Thank you for your great project. it is super awesome. 👍 

I get this error on the building project with vs 2017:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'BOOL QueryServiceConfigW(SC_HANDLE,LPQUERY_SERVICE_CONFIGW,DWORD,LPDWORD)': cannot convert argument 2 from 'QUERY_SERVICE_CONFIG *' to 'LPQUERY_SERVICE_CONFIGW'	D:\InstalledApp\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CMakeLists.txt	...\source\base\service_controller.cc	207	
```

**Comment by dchapyshev** [comment]
Hello.
Thanks for the feedback :)
1. You do not seem to have "Use Unicode Character Set" selected in project properties (Project->Properties->General->Character Set).
2. Also check that you have installed SDK 8.1.
3. I also fixed the use of structure in the code.
Update the source code, check the specified parameter and try to re-build the project.
The code must be built, this is conformed by [AppVeyor](https://ci.appveyor.com/project/dchapyshev/aspia/branch/master).

**Comment by PejmanNik** [comment]
Thank you so much. I fallow AppVeyor file and it is ok now.
sorry for that
