### ISSUE TITLE
Добавить пояснение на вкладку "Маршрутизатор" настроек хоста

### ISSUE THREAD

**Issue by Korb** [dchapyshev/aspia#118]
Сейчас после установки и запуска aspia_host.exe версии 2.1.0.0 на вкладке "Маршрутизатор" в настройках нет никаких пояснений, что именно дает активация чекбокса "Включить использование маршрутизатора", что за адрес предполагается вводить в первое поле, и что за "публичный ключ" можно (нужно?) вставить во второе поле? Для впервые сталкивающихся с этим приложением было бы полезно либо привести краткое пояснение, или, хотя бы, сделать ссылку на страницу с разъяснениями.

**Comment by dchapyshev** [comment]
Пояснения добавлены.
