### ISSUE TITLE
Problem while elevating privileges in Windows 2019

### ISSUE THREAD

**Issue by MrKitai** [dchapyshev/aspia#119]
**Describe the bug**

Using Windows 10, you can elevate your privileges using a local admin password when needed (for example, to install a program in a remote PC where the user using Aspia host have user privileges only).

But in Windows 2019, the program hangs.

**To Reproduce**

1- Connect to a remote PC where Aspia host is launched having only user permissions. Not admin.
2- Try to install a Program, to get the prompt for admin privileges.
3- In windows 2019, you cannot pass this point.

**Screenshots**

**Desktop (please complete the following information):**
- Windows Server 2019
- Aspia 2.1.0

**Comment by dchapyshev** [comment]
Fixed in 2.2.0 version.
