### ISSUE TITLE
sir we want to contribute code ,but there is something wrong with your description about build

### ISSUE THREAD

**Issue by introspection3** [dchapyshev/aspia#127]
**Describe the bug**
there is something wrong with your description about build
**To Reproduce**
1.we spent all day to install all vcpkg's package
2.but we can't generate the sln file with your descripton
![image](https://user-images.githubusercontent.com/12368358/147921722-4c776632-c84c-466e-bdfb-cc44c10b01a9.png)
**Expected behavior**
A clear description about cmake
https://user-images.githubusercontent.com/12368358/147921410-1765856c-8551-45a0-94a4-bd8eab071be7.png
**Screenshots**

**Desktop (please complete the following information):**
 - OS name and version
 - Aspia version [e.g. 1.1.0]

**Additional context**

**Comment by introspection3** [comment]
visual studio can build c++ on linux,so you can support sln directly,and user can link the lib self

**Comment by dchapyshev** [comment]
1) You have not installed the Qt packages in vcpkg or installed them with the wrong triplet.
2) Building in VS 2022 is also not officially supported. It is not guaranteed to build.
Read the instructions carefully.

**Comment by introspection3** [comment]
@dchapyshev sir, it came acrosss error when use c:/src/vcpkg.exe intall qt5-wineextras or qt5-translations???
other people got the same problem 
https://www.mail-archive.com/development@qt-project.org/msg38192.html



jom 1.1.3 - empower your cores

WARNING: Failure to find: qt5qml_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/assembler/*.h
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/wtf/*.h
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qml/qt5qml_metatypes.json
WARNING: Failure to find: qt5qmld_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/assembler/*.h
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/wtf/*.h
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qml/qt5qmld_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5qmlmodels_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlmodels/qt5qmlmodels_metatypes.json
WARNING: Failure to find: qt5qmlmodelsd_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlmodels/qt5qmlmodelsd_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5qmlworkerscript_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlworkerscript/qt5qmlworkerscript_metatypes.json
WARNING: Failure to find: qt5qmlworkerscriptd_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlworkerscript/qt5qmlworkerscriptd_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quick_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/quick/qt5quick_metatypes.json
WARNING: Failure to find: qt5quickd_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/quick/qt5quickd_metatypes.json
C:\src\vcpkg\buildtrees\qt5-declarative\src\5.15.2-30e50540ea.clean\src\quick\scenegraph\qsgrenderloop.cpp(0): Note: No relevant classes found. No output generated.
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quickshapes_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/quickshapes/qt5quickshapes_metatypes.json
WARNING: Failure to find: qt5quickshapesd_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/quickshapes/qt5quickshapesd_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quicktest_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmltest/qt5quicktest_metatypes.json
WARNING: Failure to find: qt5quicktestd_metatypes.json
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmltest/qt5quicktestd_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5test_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: labsmodelsplugin_metatypes.json
WARNING: Failure to find: qmlfolderlistmodelplugin_metatypes.json
WARNING: Failure to find: qmllocalstorageplugin_metatypes.json
WARNING: Failure to find: qmlsettingsplugin_metatypes.json
WARNING: Failure to find: qtqmlstatemachine_metatypes.json
WARNING: Failure to find: qmlsettingsplugind_metatypes.json
WARNING: Failure to find: qmlfolderlistmodelplugind_metatypes.json
WARNING: Failure to find: qmllocalstorageplugind_metatypes.json
WARNING: Failure to find: labsmodelsplugind_metatypes.json
WARNING: Failure to find: qtqmlstatemachined_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: labsanimationplugin_metatypes.json
WARNING: Failure to find: labsanimationplugind_metatypes.json
WARNING: Failure to find: qquicklayoutsplugin_metatypes.json
WARNING: Failure to find: qquicklayoutsplugind_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5sql_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qmlwavefrontmeshplugin_metatypes.json
WARNING: Failure to find: qmlwavefrontmeshplugind_metatypes.json
WARNING: Failure to find: windowplugin_metatypes.json
WARNING: Failure to find: windowplugind_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qmltestplugin_metatypes.json
WARNING: Failure to find: qmltestplugind_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: sharedimageplugin_metatypes.json
WARNING: Failure to find: sharedimageplugind_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5test_metatypes.json
WARNING: Failure to find: qml_metatypes.json
WARNING: Failure to find: qml_metatypes.json
Cannot open foreign types file C:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlprofiler\Makefile.Release [..\..\bin\qmlprofiler.exe] Error 1257
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmltestrunner\Makefile.Release [..\..\bin\qmltestrunner.exe] Error 1257
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmltestrunner\Makefile [release] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlprofiler\Makefile [release] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmltestrunner-make_first] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qml\Makefile.Release [..\..\bin\qml.exe] Error 1257
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmlprofiler-make_first] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qml\Makefile [release] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qml-make_first] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\Makefile [sub-tools-make_first] Error 2

**Comment by dchapyshev** [comment]
I don't know why you get this error. You need to look at the logs and figure out why this is happening. The information you provided is insufficient.

**Comment by introspection3** [comment]
I doubt that Qt5 windows bug @dchapyshev 
WARNING: Failure to find: C:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/assembler/.h
the file is exist,but the split char '/' is not windows's.....

**Comment by dchapyshev** [comment]
Windows work fine with '/' delimiters. This is not the cause of the problem.

**Comment by introspection3** [comment]
@dchapyshev  qt is too heavy,and it has a bad license,you can choose 
https://sciter.com

**Comment by SharsDela** [comment]
try to add this -DVCPKG_TARGET_TRIPLET=x86-windows-static command line when cmake configure.

**Comment by introspection3** [comment]
@dchapyshev we know the reason:
you should use Conan other than vcpkg

**Comment by dchapyshev** [comment]
1) I don't plan to change Qt to anything else. And there are many reasons for this:
- Qt is not only GUI. It is a framework with a lot of possibilities.
- Qt license perfectly compatible with Aspia license.
- The Sciter you specified is not licensed compatible with Aspia. Read Aspia's license agreement before making such suggestions.
2) I don't plan to change build tools because they suit me completely. With vcpkg, I build third-party libraries for Windows (x86, x86_64), Linux (x86_64), MacOS (x86_64) and Paspberry Pi (ARM64) without any problems.

Issue closed.

**Comment by introspection3** [comment]
@dchapyshev just as we know ,microsoft create so many rubish(include vcpkg),if you use conan,you will find it too fast...
