### ISSUE TITLE
Для запуска этого проекта требуется долгая и тяжелая конфигурация, и он все еще работает в конце, что мешает развитию проекта.

### ISSUE THREAD

**Issue by introspection3** [dchapyshev/aspia#128]

**Comment by introspection3** [comment]
Мы потратили несколько дней и скачали десятки гигабайт компонентов. В конце концов, мы так и не смогли запустить этот проект, как вы сказали. Можно ли упростить работу? Уважаемый сэр?

**Comment by dchapyshev** [comment]
It's impossible. Use pre-built app assemblies.

**Comment by introspection3** [comment]
Сэр, нет ничего невозможного. В настоящее время этот проект повлиял на его быстрое развитие, потому что большинство людей не могут его скомпилировать.
@dchapyshev

**Comment by dchapyshev** [comment]
What do you suggest? vcpkg makes it easier to build dependencies. Without it, you will have to build all dependencies manually according to the instructions of the manufacturers (of these libraries). This path will be many times more difficult.
The application is now very easy to build. You just need to follow the assembly instructions carefully.

**Comment by introspection3** [comment]
Сэр, если у вас совершенно новая операционная система, возможно, вы знаете, в чем проблема.

**Comment by introspection3** [comment]
@dchapyshev 
CMake Error at proto/CMakeLists.txt:39 (protobuf_generate):
  Unknown CMake command "protobuf_generate".

**Comment by introspection3** [comment]
@dchapyshev 
![image](https://user-images.githubusercontent.com/12368358/147921410-1765856c-8551-45a0-94a4-bd8eab071be7.png)

**Comment by introspection3** [comment]
do you know why?? @dchapyshev

**Comment by dchapyshev** [comment]
You don’t follow the assembly instructions on principle? All of your problems are due to this.
Why are you using triplet x86-windows instead of x86-windows-static?

**Comment by introspection3** [comment]
sir we have try it at first,but failed....

**Comment by dchapyshev** [comment]
This only means that you have not followed the other points of the instructions. You must strictly follow all points of the instructions and then everything will work out.

**Comment by introspection3** [comment]
sir, we have try it at first,but failed....
![image](https://user-images.githubusercontent.com/12368358/147926777-3309e22c-661b-49a5-81c1-b99277c7c244.png)

**Comment by dchapyshev** [comment]
Where did you get vcpkg from?

**Comment by introspection3** [comment]
> Where did you get vcpkg from?

we down vcpkg from github

**Comment by introspection3** [comment]
![image](https://user-images.githubusercontent.com/12368358/147927357-5dec7ac3-3966-421d-94e2-a43f5c22df64.png)

**Comment by dchapyshev** [comment]
According to the instructions, you should have taken vcpkg from here: https://github.com/dchapyshev/vcpkg.
Where exactly did you download vcpkg from?

**Comment by introspection3** [comment]
Oh,My God,you have created yourself vcpkg?

**Comment by dchapyshev** [comment]
There are some patches on my vcpkg fork. You have to use it. The same was written in the instructions.

**Comment by introspection3** [comment]
> There are some patches on my vcpkg fork. You have to use it. The same was written in the instructions.

sir ,thank you.my God,your action is too terrible

**Comment by dchapyshev** [comment]
I don’t know why you don’t have access to google servers.

**Comment by introspection3** [comment]
maybe you have a old libyuv version

**Comment by dchapyshev** [comment]
Sorry, but you're talking nonsense. It's you have some kind of problem accessing Google servers. Version of vcpkg was updated on December 23rd. But this cannot be a problem, there the git is called to download the specified commit. And this commit is there.

**Comment by introspection3** [comment]
😄

**Comment by introspection3** [comment]
jom 1.1.3 - empower your cores

WARNING: Failure to find: qt5qml_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/assembler/*.h
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/wtf/*.h
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/qml/qt5qml_metatypes.json
WARNING: Failure to find: qt5qmld_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/assembler/*.h
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/wtf/*.h
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/qml/qt5qmld_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5qmlmodels_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlmodels/qt5qmlmodels_metatypes.json
WARNING: Failure to find: qt5qmlmodelsd_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlmodels/qt5qmlmodelsd_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5qmlworkerscript_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlworkerscript/qt5qmlworkerscript_metatypes.json
WARNING: Failure to find: qt5qmlworkerscriptd_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlworkerscript/qt5qmlworkerscriptd_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quick_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/quick/qt5quick_metatypes.json
WARNING: Failure to find: qt5quickd_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/quick/qt5quickd_metatypes.json
G:\v\buildtrees\qt5-declarative\src\5.15.2-30e50540ea.clean\src\quick\scenegraph\qsgrenderloop.cpp(0): Note: No relevant classes found. No output generated.
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quickshapes_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/quickshapes/qt5quickshapes_metatypes.json
WARNING: Failure to find: qt5quickshapesd_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/quickshapes/qt5quickshapesd_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quicktest_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmltest/qt5quicktest_metatypes.json
WARNING: Failure to find: qt5quicktestd_metatypes.json
WARNING: Failure to find: G:/v/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmltest/qt5quicktestd_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5test_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: labsmodelsplugin_metatypes.json
WARNING: Failure to find: qmllocalstorageplugin_metatypes.json
WARNING: Failure to find: qmlsettingsplugin_metatypes.json
WARNING: Failure to find: qmlfolderlistmodelplugin_metatypes.json
WARNING: Failure to find: qtqmlstatemachine_metatypes.json
WARNING: Failure to find: qmlsettingsplugind_metatypes.json
WARNING: Failure to find: qmlfolderlistmodelplugind_metatypes.json
WARNING: Failure to find: qmllocalstorageplugind_metatypes.json
WARNING: Failure to find: labsmodelsplugind_metatypes.json
WARNING: Failure to find: qtqmlstatemachined_metatypes.json
WARNING: Failure to find: labsanimationplugin_metatypes.json
WARNING: Failure to find: labsanimationplugind_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qquicklayoutsplugin_metatypes.json
WARNING: Failure to find: qquicklayoutsplugind_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5sql_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: windowplugin_metatypes.json
WARNING: Failure to find: windowplugind_metatypes.json
WARNING: Failure to find: qmlwavefrontmeshplugin_metatypes.json
WARNING: Failure to find: qmlwavefrontmeshplugind_metatypes.json
WARNING: Failure to find: qmltestplugin_metatypes.json
WARNING: Failure to find: qmltestplugind_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: sharedimageplugin_metatypes.json
WARNING: Failure to find: sharedimageplugind_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5test_metatypes.json
WARNING: Failure to find: qml_metatypes.json
WARNING: Failure to find: qml_metatypes.json
Cannot open foreign types file G:/v/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
jom: G:\v\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmleasing\Makefile.Release [..\..\bin\qmleasing.exe] Error 1257
jom: G:\v\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmleasing\Makefile [release] Error 2
jom: G:\v\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmleasing-make_first] Error 2
jom: G:\v\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qml\Makefile.Release [..\..\bin\qml.exe] Error 1257
jom: G:\v\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qml\Makefile [release] Error 2
jom: G:\v\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qml-make_first] Error 2
jom: G:\v\buildtrees\qt5-declarative\x86-windows-static-rel\Makefile [sub-tools-make_first] Error 2

**Comment by introspection3** [comment]
@dchapyshev same problem with your vcpkg

**Comment by introspection3** [comment]
@dchapyshev  sir,this project is too terrible,it wasted our one week to configure it,but also failed,it's too sad for us...

**Comment by introspection3** [comment]
so the project can only run on your pc ,sir

**Comment by dchapyshev** [comment]
Yesterday I put together a project on a clean computer and there were no problems with the build. Many people have already built a project and they also did not have any problems.
I do not know why you are having problems. You are either not following the build instructions, or there is something wrong with your system.

**Comment by introspection3** [comment]
@dchapyshev sir ,I doubt that your words. vcpkg.exe install qt5-translations:x86-windows-static 
will not succeed,because this pkg is not support by Microsoft (Microsoft  team said)

**Comment by introspection3** [comment]
![image](https://user-images.githubusercontent.com/12368358/151474655-218472f8-7fb2-4e69-8fc8-08cd2c823def.png)
