### ISSUE TITLE
Ссылка на сервер обновлений

### ISSUE THREAD

**Issue by alexey-gamov** [dchapyshev/aspia#129]
**Is your feature request related to a problem? Please describe.**

В настоящий момент при обращении к своему серверу обновлений запрос производится по адресу, без возможности добавить свой путь до конкретной директории.

**Describe the solution you'd like**

Немного доработать код, связанный с запросом обновлений. Использовать введенный путь полностью, а дальше уже добавить _/update.php?package=..&version=.._

**Describe alternatives you've considered**

Альтернативный метод сейчас - добавить запись в _.htaccess_, где будет указан новый путь к _update.php_.

**Comment by dchapyshev** [comment]
Исправлено в версии 2.4.0.
