### ISSUE TITLE
Installer for Ubuntu 18.04

### ISSUE THREAD

**Issue by denisgolius** [dchapyshev/aspia#13]
Can you make  installer for Ubuntu 18.04 ? Or build bin files for using as portable.. Thanks!

**Comment by dchapyshev** [comment]
At the moment, only Windows is supported. Make an installer for Ubuntu impossible.

**Comment by sskras** [comment]
@dchapyshev commented on Jul 10, 2018:

> At the moment, only Windows is supported. Make an installer for Ubuntu impossible.

I would say that doing an installer is not impossible – it would probably be just unusual and unexpected.

And doing a really portable binary for running on every Linux versions and several machine architectures (x86*, ARM*, RISC-V) found around would truly be a big project by itself.  Not an impossible one too.
