### ISSUE TITLE
Windows IME support

### ISSUE THREAD

**Issue by epilogs** [dchapyshev/aspia#131]
Hello.

Thank you for maintaining the Aspia project.
It's a really cool project.

However, if there is one disappointment, it is that IME function is not supported.

Whenever necessary to change the language input method, I used to click the IME switch button in the system tray with the mouse.

It would be even nicer if it could be improved so that when the IME toggle button on the keyboard is pressed, it is delivered to the remote via aspia.

I tried to edit the source code myself, but for some reason the build failed and I couldn't proceed further, so I want to get your help.
As you know, related Windows messages and Virtual Keys are as follows.

WM_IME_CHAR
WM_IME_COMPOSITION
WM_IME_COMPOSITIONFULL
WM_IME_CONTROL
WM_IME_ENDCOMPOSITION
WM_IME_KEYDOWN
WM_IME_KEYUP
WM_IME_NOTIFY
WM_IME_REQUEST
WM_IME_SELECT
WM_IME_SETCONTEXT
WM_IME_STARTCOMPOSITION

VK_KANA       IME Kana mode
VK_HANGUL     IME Hangul mode
VK_IME_ON     IME On
VK_JUNJA      IME Junja mode
VK_FINAL      IME final mode
VK_HANJA      IME Hanja mode
VK_KANJI      IME Kanji mode
VK_IME_OFF    IME Off
VK_CONVERT    IME convert
VK_NONCONVERT IME nonconvert
VK_ACCEPT     IME accept
VK_MODECHANGE IME mode change request

**Comment by dchapyshev** [comment]
Hello.
Aspia doesn't know anything about keyboard layouts, languages, and so on. And the application does not need to know this.
The application does not transmit character codes over the network, but transmits key codes. For each button on the keyboard, this is always the same code (regardless of the layout).
You need to switch the keyboard layout with a key combination on the remote machine (where the host is installed). The combination on the client side may be different from the combination on the remote computer.

**Comment by epilogs** [comment]
Thanks for your reply.
