### ISSUE TITLE
Console/client deb install in ubuntu 20.04

### ISSUE THREAD

**Issue by vGimly** [dchapyshev/aspia#135]
**Describe the bug**
Установка пакетов aspia-client-2.2.1-x86_64.deb  aspia-console-2.2.1-x86_64.deb
в системе ubuntu 20.04
приводит к сообщениям об ошибках в зависимостях от пакета
libxcb-util0 (>=0.3.8), отсутствующего в репозиториях.

**To Reproduce**
sudo dpkg -i aspia-client-2.2.1-x86_64.deb 
Выбор ранее не выбранного пакета aspia-client.
Подготовка к распаковке aspia-client-2.2.1-x86_64.deb …
Распаковывается aspia-client (2.2.1) …
dpkg: зависимости пакетов не позволяют настроить пакет aspia-client:
 aspia-client зависит от libxcb-util0 (>= 0.3.8), однако:
  Пакет libxcb-util0 не установлен.
dpkg: ошибка при обработке пакета aspia-client (--install):
 проблемы зависимостей — оставляем не настроенным
При обработке следующих пакетов произошли ошибки:
 aspia-client

$ aspia_client 
aspia_client: error while loading shared libraries: libxcb-util.so.0: cannot open shared object file: No such file or directory

**Expected behavior**
Установка и работа без ошибок.

**Desktop (please complete the following information):**
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Additional context**
В стандартных репозиториях имеется пакет libxcb-util1:amd64 0.4.0-0ubuntu3 - который устанавливает в системе библиотеку /usr/lib/x86_64-linux-gnu/libxcb-util.so.1
При создании симлинка libxcb-util.so.0 на этот файл всё успешно работает.

**Comment by vGimly** [comment]
[libxcb-util0_0.4.0-1.zip](https://github.com/dchapyshev/aspia/files/7993363/libxcb-util0_0.4.0-1.zip)
Предлагаю deb файл-заглушку, который делает этот симлинк, что исправляет зависимости deb файлов и работу aspia_client и aspia_console.

**Comment by dchapyshev** [comment]
Проблема в том, что я собираю релизы в Debian 10.3 и там используется libxcb-util0, а в Ubuntu 20.04 используется libxcb-util1. Со следующего релиза сборка будет переведена на Debian 11 (там та же версия этой библиотеки, что и в Ubuntu) и проблема решится сама собой.

**Comment by dchapyshev** [comment]
Проблема исправлена в версии 2.3.0. Официально поддерживается Ubuntu 20.04 и Debian 11. При использовании данных дистрибутивов проблем быть не должно.
