### ISSUE TITLE
Contributing to Chinese (Traditional) translation

### ISSUE THREAD

**Issue by ukewea** [dchapyshev/aspia#137]
**Is your feature request related to a problem? Please describe.**
I would like to translate UI for 'Chinese (Traditional)', am I on my own to generate those `.ts` files, or can the devs generate those for the translator?

**Describe alternatives you've considered**
There already exists 'Chinese (China)' translation, made with Simplified Chinese characters. I would like to add a translation (Chinese (Taiwan) to be specific) using Traditional Chinese characters instead.

Thanks for the awesome solution for desktop management!

**Comment by dchapyshev** [comment]
Files for translation added in the commit ea4da7a37ad96ed7f9cb9d5b5182b454b004a409.
