### ISSUE TITLE
VariableSizeReader::buffer size may mistake

### ISSUE THREAD

**Issue by iByteSpace** [dchapyshev/aspia#138]
[The size of VariableSizeReader::buffer_  ](https://github.com/dchapyshev/aspia/blob/master/source/base/net/variable_size.h#L56) is 4 bytes.

But mutable_buffer of VariableSizeReader::buffer returned is 1 byte [(sizeof(uint8_t)).](https://github.com/dchapyshev/aspia/blob/master/source/base/net/variable_size.cc#L33 )

So from[ asio::read](https://github.com/dchapyshev/aspia/blob/master/source/base/net/network_channel.cc#L568), you can only read 1 byte at most. This may be an error.

**Comment by dchapyshev** [comment]
It's not a error. This is a buffer that is written byte by byte. In this case, each of the bytes can be the last. This is indicated by the name of the class - VariableSizeReader.
