### ISSUE TITLE
Клиентская часть отдельно от серверной?

### ISSUE THREAD

**Issue by lumenvindex** [dchapyshev/aspia#15]
Планируется ли разделять установщик - клиент+сервер, только клиент, только сервер? Будет ли портативная (не требующая установки) версия?

**Comment by dchapyshev** [comment]
Текущая архитектура не позволяет красиво разделить их. Есть core библиотека и я использую статическую линковку со сторонними библиотеками (в том числе с Qt). Исполняемые файлы просто вызывают функции из этой библиотеки. Разделение будет означать дублирование почти всего кода в 2 экземплярах и увеличение размера приложения в 2 раза. Этого мне делать не хотелось бы.
Вы можете не устанавливать серверную часть (она опциональная), но консоль ставится в любом случае.
Сейчас портативная версия отсутствует, но возможно просто скопировать файлы из Program Files, а потом удалить приложение. Если вам не нужен сервер при этом, то вы просто можете удалить исполняемые файлы, названия которых начинаются на host_*. Серверная часть без установки службы не работает.

**Comment by lumenvindex** [comment]
По поводу разделения всё ясно. Может всё-таки есть смысл сделать возможным установку и только серверной части, без консоли? Было бы полезно при использовании в организациях - рядовым пользователям не нужна клиентская часть. Понятно, что можно установить обе части, а потом поудалять лишнее, но это лишние костыли...

**Comment by lumenvindex** [comment]
Я с WiX никогда не сталкивался, но ответы вроде как тут:
https://www.firegiant.com/wix/tutorial/user-interface-revisited/customizations-galore/
https://stackoverflow.com/questions/9328619/wix-conditional-install-of-features-based-on-radio-buttons

**Comment by IvvanVG** [comment]
Поддерживаю, клиентам нужна только серверная часть.

**Comment by legionpheonix** [comment]
Плюсуюсь!

**Comment by dchapyshev** [comment]
Ваша проблема исправлена в версии 1.1.0. Обращение будет закрыто. Если вы считаете, что проблема не исправлена, то можете открыть его снова.
