### ISSUE TITLE
Aspia Console Import/Export

### ISSUE THREAD

**Issue by yasinvs** [dchapyshev/aspia#150]
// Translated :)

*English*
Hello,
Any chance you can add list export/import functionality in "Aspia Console"? In CSV or XML or Excel format ?
Kind regards

*Russian*
Привет,
Есть ли шанс, что вы можете добавить функцию экспорта/импорта списка в «Консоль Aspia»? В формате CSV или XML или Excel?
С уважением

*Turkish*
Selamlar,
"Aspia Console" uygulamasında listeyi dışa/içe aktarma işlevi ekleyebilme şansınız var mıdır? CSV veya XML veya Excel formatında ?
Saygılarımla

**Comment by yasinvs** [comment]
++

**Comment by dchapyshev** [comment]
Import and export to JSON are implemented in 2.6.0.
