### ISSUE TITLE
Check Mark when PC goes online

### ISSUE THREAD

**Issue by felipeborela** [dchapyshev/aspia#151]
![imagem_2022-04-10_222435861](https://user-images.githubusercontent.com/9823628/162650111-a38756b6-433a-40da-81cf-329b12c5d151.png)
Hello, I would like to make a suggestion.
I used Radmin Viewer for a long time and there is a function that when I press F5 it shows all computers online with a "check mark" on the computer icon.
It would be awesome if it had this function in Aspia too!

**Comment by dchapyshev** [comment]
Implemented in 2.5.0 release.
