### ISSUE TITLE
Client/Console is overscaled on high DPI

### ISSUE THREAD

**Issue by CaptainFlint** [dchapyshev/aspia#159]
Windows 10, DPI is set to 150%. When I start Aspia client or console (have not checked other components), the UI is scaled too much, looks like 200% or so.

Here are some screenshots.
1. How Console looks with normal 100% scaling.
<img width="381" alt="console-dpi-100" src="https://user-images.githubusercontent.com/6475044/167962674-ed2082f0-8914-449f-8f3a-ce66e968497f.png">
2. The previous image streched to 150% in an image editor, as an illustration of what I would expect to see.
<img width="571" alt="console-dpi-100-to-150" src="https://user-images.githubusercontent.com/6475044/167962679-99b51b97-3553-4db2-9b34-7af19a271aa6.png">
3. What Console actually looks like when Windows DPI is set to 150%.
<img width="531" alt="console-dpi-150" src="https://user-images.githubusercontent.com/6475044/167962682-c83cb817-ee23-4866-965a-2deecff31d4f.png">

You can see that the window titlebar is approximately the same in the 3rd and the 2nd images. It means, that OS shows the system window areas scaled to 150%, just as expected. However, the internal client area elements (fonts, icons, etc.) are way too big in the 3rd image.

I have not looked at the code, but is it possible that, for example, Qt already takes care of all the scaling, and you then add your own scaling on top of that?

OS: Windows 10 x64 1909
Aspia 2.4.0.

**Comment by dchapyshev** [comment]
All scaling is handled by Qt. Aspia does not control it.

**Comment by CaptainFlint** [comment]
I have other Qt applications, and they don't do such an over-scaling, but show elements with normal 150% size, as expected.

**Comment by CaptainFlint** [comment]
I googled a bit, and it seems the issue with Qt scaling by 200% when Windows is set at 150% is a known behavior, it just rounds it to the nearest integer which is 2 (200%). To avoid this, it's recommended to use [QGuiApplication::highDpiScaleFactorRoundingPolicy](https://doc.qt.io/qt-5/qguiapplication.html#highDpiScaleFactorRoundingPolicy) with policy set to PassThrough.

I tried overriding the policy using environment variable QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough, and, indeed, the scale became consistent with the OS.

**Comment by dchapyshev** [comment]
Thanks for your research into the problem. I will try to take this into account in the next release.

**Comment by dchapyshev** [comment]
Fixed in 2.5.0 version.

**Comment by 940842546** [comment]
> Fixed in 2.5.0 version.
no, it's already exists
As a comparison,set system environment variables Qt_ENABLE_HIGHDPI_SCALING=0 and QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough,it's not overscaled
![image](https://user-images.githubusercontent.com/8674798/211237780-98f5976d-e16b-4458-9219-e2753cd4024c.png)

**Comment by dchapyshev** [comment]
In the original problem, it was described that the application looks larger than other applications on the system. This issue has been fixed and now the app size looks the same as other apps.
When you set the Qt_ENABLE_HIGHDPI_SCALING parameter to 0, the application completely stops adjusting to the DPI in the system. This is incorrect behavior. The application must be able to scale according to the DPI. Moreover, in Qt 6, the Qt_ENABLE_HIGHDPI_SCALING parameter is declared obsolete and scaling is always enabled.
High DPI scaling disabled:
![high_dpi_scaling_false](https://user-images.githubusercontent.com/4012402/211294133-8b797b8c-df17-44cf-bb8e-f6e2f31e77f3.PNG)
High DPI scaling enabled:
![high_dpi_scaling_true](https://user-images.githubusercontent.com/4012402/211294142-50c6bddc-bd77-46bf-a7c5-2bbcb8b564e6.PNG)

**Comment by 940842546** [comment]
> In the original problem, it was described that the application looks larger than other applications on the system. This issue has been fixed and now the app size looks the same as other apps. When you set the Qt_ENABLE_HIGHDPI_SCALING parameter to 0, the application completely stops adjusting to the DPI in the system. This is incorrect behavior. The application must be able to scale according to the DPI. Moreover, in Qt 6, the Qt_ENABLE_HIGHDPI_SCALING parameter is declared obsolete and scaling is always enabled. High DPI scaling disabled: ![high_dpi_scaling_false](https://user-images.githubusercontent.com/4012402/211294133-8b797b8c-df17-44cf-bb8e-f6e2f31e77f3.PNG) High DPI scaling enabled: ![high_dpi_scaling_true](https://user-images.githubusercontent.com/4012402/211294142-50c6bddc-bd77-46bf-a7c5-2bbcb8b564e6.PNG)

nono
i mean the display
the display is overscale
this is the compare with teamviewer
![image](https://user-images.githubusercontent.com/8674798/212300514-0ee3e3d4-571b-4b38-bab7-5b82b6840c86.png)
