### ISSUE TITLE
Поддержка устаревших ОС

### ISSUE THREAD

**Issue by IvvanVG** [dchapyshev/aspia#16]
Добрый день! Можете реализовать поддержку ОС начиная с Windows XP/2003?
В серверном сегменте государственных служб еще очень много таких систем(
![aspia_install_2003](https://user-images.githubusercontent.com/8935752/42547741-4233beac-84f6-11e8-8e05-8406abf8ccf9.jpg)
![aspia_service_2003](https://user-images.githubusercontent.com/8935752/42547742-4265b830-84f6-11e8-9abd-61882663009d.jpg)

**Comment by dchapyshev** [comment]
К сожалению, это невозможно. Qt, начиная с версии 5.6, прекратила поддержку ХР. Программа же полностью написана с использованием Qt.

**Comment by eugeny54** [comment]
А вот тут приводится решение этой проблемы - https://bugreports.qt.io/browse/QTBUG-50188
Посмотрите, вдруг получится.
Было бы очень приятно запустить вашу программу под Windows XP.
Многие сказали бы спасибо.

**Comment by badenru** [comment]
поддерживаю просьбу. здесь альтернативы (vnc и прочие) в преимуществе..

**Comment by dbelyaev** [comment]
@eugeny54 разве это не workaround конкретно для версии 5.6 и вероятность того, что оно отвалиться в следующих версиях очень велик (учитывая то как Digia переписывает внутренности Qt в последнее время, выкидывая на помойку устаревшие модули)?

**Comment by dchapyshev** [comment]
Qt уже очень активно использует функции из Vista+ внутри себя. И чем дальше, тем больше этого будет. Это никак не отключить и не исправить. Любые попытки сделать это приведут только к проблемам.

**Comment by Ivan4848** [comment]
Поддержу за windows xp, если вашу программу использовать для техподдержки, то 10-15 клиентов, лично у меня на windows xp и ничего другого туда не встанет :(

**Comment by dbelyaev** [comment]
@Ivan4848 @badenru  автор использует Qt SDK и с каждой новой версией они убирают поддержку legacy ОС. К сожалению, с этим ничего не поделать, а любые workaround и патчи лишь усложнят разработку программы (часть SDK придеться пересобирать и деплоить со своими кастомными версиями бинарников).

Оффициально поддерживаемые платформы в Qt:

- [Qt v5.6 LTS](http://doc.qt.io/qt-5.6/supported-platforms.html) (еще есть поддержка Windows XP)
- [Qt v5.8](https://doc.qt.io/archives/qt-5.8/supported-platforms.html) (убрали Windows XP и Виста)
- [Qt v5.11](http://doc.qt.io/qt-5/supported-platforms.html) (добавили поддержку Windows UWP)

[Полный список актуальных версий и поддерживаемых платформ](https://wiki.qt.io/PlatformSupport)

Судя по [коммиту](https://github.com/dchapyshev/aspia/commit/69895d82c799db369ccc3feca84326723b9bcbc0), релизная версия v1.0.0 в master использует Qt v5.11.1.
