### ISSUE TITLE
Настройка прокси

### ISSUE THREAD

**Issue by unwo** [dchapyshev/aspia#17]
Добрый день.
Можно ли вынести настройки прокси в отдельное окно. Сейчас используются системный, но не всегда компьютеры находятся в той же подсети (т.е. галка "Не использовать прокси-сервер для локальных адресов" не работает) необходимо добавлять каждый компьютер в исключение крайне не удобно. Может сделать настройки как выбор в firefox.

**Comment by dchapyshev** [comment]
Добрый день.
Программа не поддерживает работу через прокси-сервер, и соответственно, не использует его. Все подключения устанавливаются напрямую.

**Comment by unwo** [comment]
Странно. Когда в Internet Explorer стоит галка Использовать прокси-сервер, то приложение выдает:
17:46:33 Попытка подключения к 192.168.10.2:8050.
17:46:33 Сетевая ошибка: Прокси-сервер запретил соединение
При отключению прокси сервера в Internet Explorer - происходит подключение.
Сейчас попробовал добавить в исключение в логе: 
17:48:00 Сетевая ошибка: Некорректный тип прокси-сервера для данной операции.

**Comment by dchapyshev** [comment]
Есть вероятность, что Qt использует параметры прокси-сервера как-то неявно. Попробую разобраться, как будут результаты - отпишусь.

**Comment by badenru** [comment]
подтверждаю . без выключения системного прокси на клиенте получим "Некорректный тип прокси-сервера для данной операции."

**Comment by AlexObukhoff** [comment]
Если бы ещё реализовали работу через прокси с авторизацией Negotiate, цены бы не было программе!

**Comment by dchapyshev** [comment]
В Qt, а соответственно и в моей программе, как оказалось уже есть поддержка прокси, хотя и не совсем запланированная и работающая не пойми как :)
Осталось сделать настройку этого прокси. Будет поддерживаться ровно на том уровне, на каком его поддерживает Qt. Почитать о том, что в этом плане поддерживает Qt, можно [здесь](http://doc.qt.io/qt-5/qnetworkproxy.html).

**Comment by dchapyshev** [comment]
Проблема исправлена. Поддержки прокси на данный момент нет, системный прокси так же не должен использоваться.
Просьба проверить и сообщить о результатах.
Скачать обновленную версию можно по ссылкам:
[https://aspia.org/files/aspia-setup-1.0.1-x86.exe](https://aspia.org/files/aspia-setup-1.0.1-x86.exe) (установщик)
[https://aspia.org/files/aspia-1.0.1-x86.7z](https://aspia.org/files/aspia-1.0.1-x86.7z) (архив)

**Comment by unwo** [comment]
Да, работает. Системный прокси не влияет на работоспособность.
