### ISSUE TITLE
Сортировка подпапок в корневой папке Aspia Console

### ISSUE THREAD

**Issue by DiWizard** [dchapyshev/aspia#174]
В данный момент, как я понимаю, сортировка в Root group отсутствует и подпапки выстраиваются по мере их создания. Это довольно не удобно.  Было бы здорово добавить возможность сортировки или хотя бы изначально сорировать подпапки по алфавиту.

**Comment by 3man001** [comment]
@DiWizard  https://github.com/dchapyshev/aspia/commit/2a6803e08cff2529719065539dacce9189d8d8cb
В ближайшем релизе должна появиться сортировка по алфавиту

**Comment by dchapyshev** [comment]
Исправлено в версии 2.5.0.
