### ISSUE TITLE
Вывод справки по параметрам командной строки в командной строке

### ISSUE THREAD

**Issue by 3man001** [dchapyshev/aspia#179]
Сейчас данная справка отображается в отдельном окне, что неудобно по нескольким причинам:
1. Окно не масштабируется из-за чего при выводе большого списка команд оно просто не умещается на экране и из-за этого не видно часть информации.
2. Нет возможности выделить и скопировать параметры и значения, приходится перепечатывать.
Отображение этой информации в командной строке позволяет избежать этих проблем.
![2022-06-25_10-51](https://user-images.githubusercontent.com/45732512/175760628-6f31372c-1dd5-4177-b79b-e21c05f96572.png)

**Comment by dchapyshev** [comment]
GUI приложения в Windows не могут ничего выводить в командную строку, а aspia_client.exe является именно таким приложением.
