### ISSUE TITLE
Не отображать на клиенте список подключений

### ISSUE THREAD

**Issue by unwo** [dchapyshev/aspia#18]
Добавить в конфигурацию сервера - не отображать правое окно подключений. Или запрет на возможность отключения подключенных.

**Comment by dchapyshev** [comment]
С этим есть одна принципиальная сложность: чтобы антивирусы относились к программе лояльно, требуется явное уведомление пользователя о наличии подключения к его компьютеру.
Реализовать возможно, только последствия будут не самые хорошие.
В запретам на отключение подключенных уже проще. Такая идея есть, реализую.

**Comment by sardigital** [comment]
Вот запрет на отключение это самая нужная нам вещь, все остальное устраивает или можно свыкнуться

**Comment by andreymal** [comment]
TightVNC не уведомляет (только едва видимый значок в трее меняет), и Касперский вроде бы не ругается

**Comment by dchapyshev** [comment]
Отключить окно уведомлений невозможно. Это одно из требований антивирусных компаний для того, чтобы приложение было в белых списках.
Данный вопрос не обсуждается.
