### ISSUE TITLE
How to change default admin/admin in router and client scaling question.

### ISSUE THREAD

**Issue by droncheg** [dchapyshev/aspia#182]
Hello. Thanks for this great application! Can't find options in router.json to setup login and password. Default is admin/admin which insecure.

Router and relay installed on same public VM with Ubuntu 20.04.

Also i have another question, not so important. In client application there's scaling feature. But it scale proportionally, can you implement in future releases option scale to fit all window?

**Comment by lumian** [comment]
How to change admin password: 
In Aspia Console: Tools -> Router Manage -> Users, select "admin" and click "Edit" (pencil icon)

**Comment by Urvdmih** [comment]
Может эту информацию в документацию добавить необходимо? А то ставишь роутер, пишет не забудьте сменить, а как - не написано. Кроме того не ясно, почему нельзя сменить пароль через консоль.

**Comment by dchapyshev** [comment]
> Может эту информацию в документацию добавить необходимо? А то ставишь роутер, пишет не забудьте сменить, а как - не написано. Кроме того не ясно, почему нельзя сменить пароль через командную строку (cmd).

Эта информация есть в [документации](https://aspia.org/docs/console#router-manage), но ее обычно никто не читает.
