### ISSUE TITLE
Can the host id start with a specified number

### ISSUE THREAD

**Issue by BiaoGe2399** [dchapyshev/aspia#193]
If i can,where should i rewrite?
host id only for one start,is not beautiful.

**Comment by BiaoGe2399** [comment]
I want to start with the specified number

**Comment by 3man001** [comment]
@BiaoGe2399, You need to open the router.db3 database for editing.
Then change the value of the "id" of the last entry in the "hosts" table.
For example using DB Browser for SQLite.
![image](https://user-images.githubusercontent.com/45732512/201534087-05249ebc-cd5f-4ddd-84f9-02b6ce4b94ef.png)

**Comment by BiaoGe2399** [comment]
> @BiaoGe2399, You need to open the router.db3 database for editing. Then change the value of the "id" of the last entry in the "hosts" table. For example using DB Browser for SQLite. ![image](https://user-images.githubusercontent.com/45732512/201534087-05249ebc-cd5f-4ddd-84f9-02b6ce4b94ef.png)

ok,thank you very much
