### ISSUE TITLE
ПОЖАЛУЙСТА освободите свою программу 

### ISSUE THREAD

**Issue by Mikrizi** [dchapyshev/aspia#202]
Очень прошу, сделайте отдельную версию, или отвяжите основную от обязательного использования DBUS, SystemD, pulseaudio 

Нету возможности пользоваться aspia на init-freedom системе, спасибо!

**Comment by Mikrizi** [comment]
Error whiile loadinng shared libraries: libdbus-1.so.3

**Comment by Mikrizi** [comment]
Error whiile loadinng shared libraries: libdbus-1.so.3

**Comment by dchapyshev** [comment]
Aspia не использует dbus в своем коде, но его использует Qt. PulseAudio не обязательный компонент, Aspia может работать без него (но не будет поддержки звука). В коде нет ничего связанного с systemd, не хотите - не используйте его. Напишите свои скрипты для запуска демонов.
Я не могу один поддерживать все возможные дистрибутивы Linux. На себя я взял поддержку Debian и Ubuntu. Будут желающие поддерживать другие дистрибутивы - будет их поддержка.

**Comment by Mikrizi** [comment]
Благодарю за ответ, aspia единственная адекватная программа удалённого доступа которая имеет поддержку обхода NAT, к сожалению QT душит и требует dbas. Надеюсь появятся люди которые сделают GTK порт.
