### ISSUE TITLE
Aspia Console закрывается при попытке закрыть вкладку адресной книги

### ISSUE THREAD

**Issue by lumian** [dchapyshev/aspia#205]
**Describe the bug**
Ошибочное закрытие или крах Aspia Console после попытки закрыть адресную книгу. Баг отрабатывает только после одновременного открытия трёх и более адресных книг. Закрепление адресных книг ни на что не влияет. Баг отработал и с двумя закрепленным книгами и без закрепления. Главное условие: крах происходит на трёх и более открытых книги.

**To Reproduce**
1. Открыть три и более адресные книги одновременно
2. Попытаться закрыть адресную книгу через ПКМ -> Закрыть вкладку или по нажатию на "Крестик" рядом с названием вкладки.
3. Консоль крашится

**Expected behavior**
Ожидалось закрытие адресной книги без закрытия консоли.

**Desktop (please complete the following information):**
 - OS: Windows 10, 1809 (17763.3650
 - Aspia version 2.5.2

**Comment by denisovbaggio** [comment]
Win7x64 
console 2.5.2.4258
открыл три книги - прекрасно закрыл. Книги были как шифрованные так и нет.

**Comment by dchapyshev** [comment]
Исправлено в 2.6.0.
