### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by Guddiny** [dchapyshev/aspia#21]
Возможно ли использовать без установки?

**Comment by lumenvindex** [comment]
> Если вам не нужен сервер при этом, то вы просто можете удалить исполняемые файлы, названия которых начинаются на host_*. Серверная часть без установки службы не работает.
https://github.com/dchapyshev/aspia/issues/15#issuecomment-403887690

**Comment by Guddiny** [comment]
Спасибо.
