### ISSUE TITLE
Добавить возможность автоматического обновления

### ISSUE THREAD

**Issue by Diversus23** [dchapyshev/aspia#22]
В случае выхода новой версии, было бы здорово, если бы программа умела автоматически обновляться.

**Comment by dchapyshev** [comment]
Такая возможность есть в TODO, реализована будет. Звучит только немного иначе: "Возможность удаленной установки и обновления программы"

**Comment by dchapyshev** [comment]
Ваша проблема исправлена в версии 1.1.0. Обращение будет закрыто. Если вы считаете, что проблема не исправлена, то можете открыть его снова.
