### ISSUE TITLE
Add a function setting to host that does not pop up a prompt window

### ISSUE THREAD

**Issue by kuerme** [dchapyshev/aspia#223]
Add a function setting to host that does not pop up a prompt window. Every time I connect to the host client, a pop-up window will cause interference to the running RPA program.

![screenshot-20230426-114747](https://user-images.githubusercontent.com/2811986/234465176-e029ae53-cab0-4878-8984-484e7e4bbfda.png)
add a setting to hide the pop-up window above

**Comment by dchapyshev** [comment]
This is not possible for privacy and security reasons. The user on the host side needs to know that a connection is being made to his computer. Anti-virus companies also make this requirement. Sorry, but this feature will never be added.

**Comment by ahdung** [comment]
@dchapyshev Administrator is your friend, not end user. If it must popup, can you auto hide it when finish remote connection? Ordinary users are usually stupid and will panic at any unfamiliar popup thing.

**Comment by ahdung** [comment]
@kuerme 这作者没产品思维，底层性能很优秀，应用层面很拉跨。
