### ISSUE TITLE
hi, for the host server private key?

### ISSUE THREAD

**Issue by michaelqxd** [dchapyshev/aspia#226]
After reviewing the code, I could not find any instance where the private key was set for the host server. Even though the code is attempting to create a TLS connection without the private key, it is unclear whether the connection would work as expected.

**Comment by dchapyshev** [comment]
Aspia does not use TLS. Aspia uses its own encryption protocol. Private and public keys are not used in this protocol.
Read about [SRP](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol), AES256 GCM and ChaCha20+Poly1305.
