### ISSUE TITLE
windows link protobuf dll file case build failed

### ISSUE THREAD

**Issue by xtayaitak** [dchapyshev/aspia#232]
**Describe the bug**
windows link protobuf dll file case build failed.

F:\study\vcpkg\installed\x86-windows\debug\bin\libprotobuf-lited.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x338

![aaaaaa](https://github.com/dchapyshev/aspia/assets/4498459/8d28824b-351c-4021-bef3-d2f6298bfc25)

**To Reproduce**
windows cmake build

**Desktop (please complete the following information):**
 - windows
 -  master version 2.6.0

**Comment by dchapyshev** [comment]
You didn't read the build documentation carefully. The documentation says to use triplet x86-windows-static, but you use x86-windows.

**Comment by xtayaitak** [comment]
@dchapyshev i see.thanks.
