### ISSUE TITLE
DesktopAgent Exit Crash Bug Fix

### ISSUE THREAD

**Issue by xtayaitak** [dchapyshev/aspia#234]
**Describe the bug**
DesktopAgent Exit Crash When Application Exit.

**Expected behavior**
20:40:23.866 21628 F message_window.cc:38 base::win::MessageWindow::~MessageWindow] Check failed: (thread_checker_).calledOnValidThread(). 

![image](https://github.com/dchapyshev/aspia/assets/4498459/eb31c330-5ed6-4ad0-9eec-e7abce3a72d0)

**Screenshots**

Fix:

DesktopSessionAgent's message_window_ was created from onBeforeThreadRunning,but onBeforeThreadRunning call from "ui_thread_".
So This code fix cant fix it.
![image](https://github.com/dchapyshev/aspia/assets/4498459/b29ab244-7024-4f10-8991-100ddb809026)

**Comment by dchapyshev** [comment]
Fixed in commit ed358b2. Thanks!
