### ISSUE TITLE
Не работают привычные горячие кнопки в адресной книге

### ISSUE THREAD

**Issue by Diversus23** [dchapyshev/aspia#24]
В адресной книге не очень удобно редактировать записи.
Обычно какая-то реакция на нажатия должна быть.
Нажимаю Enter - Должно подключасть (как будто нажали два раза левой кнопкой мыши)
Нажимаю F2 - перехожу в режим редактирования
Нажимаю Del - и должен выдаваться запрос на удаление контакта из списка.
Нажимаю Insert - добавляется новый контакт.

**Comment by dchapyshev** [comment]
Спасибо за идеи! Однозначно будет реализовано. Добавил в TODO.

**Comment by Diversus23** [comment]
> Спасибо за идеи! Однозначно будет реализовано. Добавил в TODO.
Выложили бы ToDo List в репозитарий в корне проекта, чтобы не задавали те вопросы, которые там уже есть :)

**Comment by dchapyshev** [comment]
В Teleram создана группа @aspia_ru, выкладываю обновленный TODO там, за 1-2 дня он сформируется и добавлю его в виде задач сюда.

**Comment by dchapyshev** [comment]
Ваша проблема исправлена в версии 1.1.0. Обращение будет закрыто. Если вы считаете, что проблема не исправлена, то можете открыть его снова.
