### ISSUE TITLE
Aspia client 2.4.2 / file transfer: launching more transfer requests causes the previous one(s) to freeze

### ISSUE THREAD

**Issue by nautilus1905** [dchapyshev/aspia#250]
Aspia client 2.4.2 / file transfer.  When a file or selection of files are launched accidentally during a not yet finished one, a new window appears, but the first transfer remains frozen and there is no way to close its window.
Regards

**Comment by dchapyshev** [comment]
Version 2.4.2 is outdated and no longer supported. Update the application.
