### ISSUE TITLE
Remote sound (2.6.4)

### ISSUE THREAD

**Issue by Urvdmih** [dchapyshev/aspia#254]
После обновления до 2.6.4 перестала работать передача звука с хоста.

**Comment by dchapyshev** [comment]
Никаких изменений в плане звука не было. Проверил - звук работает.
Убедитесь, что звук действительно есть (что-то воспроизводится), что он включен в системе на обеих сторонах соединения и что его передача включена в Aspia.

**Comment by Urvdmih** [comment]
Если хост на 2.5.2 звук идет, если на 2.6.4 - нет. Версия клиента при этом не влияет, передача звука включена. Проверял используя AnyDesk (через него звук идет, закрываю, в Аспии звука нет).

**Comment by dchapyshev** [comment]
Я не могу повторить проблему, все работает. Предоставьте логи хоста, клиента/консоли и скриншот окна "Статистика".

**Comment by Urvdmih** [comment]
Не могу предоставить логи по причинам связанным с ИБ. Буду надеяться в следующих версиях само пройдет.
