### ISSUE TITLE
Update aspia_host_pt-BR.ts and aspia_console_pt-BR.ts

### ISSUE THREAD

**Issue by felipeborela** [dchapyshev/aspia#255]
Update aspia_host_pt-BR.ts and aspia_console_pt-BR.ts

Hello!
As Aspia updated, I revised the translation file I made some time ago, and updated the translation

Could you merge it into the project please?

Sorry if I'm not doing it the right way. Thanks!

[aspia_pt-BR.zip](https://github.com/dchapyshev/aspia/files/13340246/aspia_pt-BR.zip)

**Comment by dchapyshev** [comment]
Hello. Ready.

**Comment by felipeborela** [comment]
My name would look really nice on the list of translators :D
