### ISSUE TITLE
Парочка пожеланий

### ISSUE THREAD

**Issue by Ivan4848** [dchapyshev/aspia#27]
1) Если нет подключения, пытаться понять почему его нет, т.е. что блокирует, ну и выдыавать запрос с возможность по переходу на другой свободный порт, на случай если текущий закрыт и т.д. 
2) Скан всего что относится к данной программе на контрольные суммы, при этом контрольные суммы брать с сервера, т.е. переда запуском проверили контрольные суммы установленных файлов, все ок, пошли дальше. Не совпало - "Файлы программы Aspia изменены (контрольные суммы файлов не верны), возможно на компьютере вирусы или жесткий диск поврежден" ну или что-то в этом духе. Ну и "список файлов с изменным CRC" / "Все равно запустить" / "выход"
3) Если в момент работы у клиента пропал интернет - не тупо виснуть, а выдать, что удаленный компьтер перестал передавать трафик, если у нас пропал интернет, что тоже бывает, выдавать что у нас.

**Comment by lumenvindex** [comment]
> запрос с возможность по переходу на другой свободный порт, на случай если текущий закрыт

Вы точно понимаете, о чём говорите? Если связи с удалённым компьютером нет, как предлагается передать ему запрос на смену порта? Смена порта в клиентской части ведь не даст вообще ничего, если серверная часть на удалённом комп-е остаётся настроена на недоступный порт.

**Comment by Ivan4848** [comment]
Я про локальный.

**Comment by dchapyshev** [comment]
1. Определить причину невозможности подключения никак нельзя, это может быть все, что угодно и где угодно.
2. Файлы приложение подписаны электронной подписью. CRC не нужны.
3. Тут все ограничено фундаментальными принципами протокола TCP. Нет никакой возможности определить, что соединение оборвано, не послав какие-либо данные. Если данные не удается отправить, то по таймауту рвется соединение. Даже если сама сессия не передает никаких данных, то каждые 30 секунд передается 1 байт равный нулю (pinger), если данные доходят, то сессия продолжает жить, если нет, то разрыв. Но мгновенно определить, что соединения вдруг не стало - нельзя. Это могут быть просто задержки по пути.

**Comment by legionpheonix** [comment]
Что-то какие-то пожелания нереальные и нереализуемые в связи с ограничением tcp и windows доступа.

**Comment by legionpheonix** [comment]
> Вы точно понимаете, о чём говорите? Если связи с удалённым компьютером нет, как предлагается передать ему запрос на смену порта? Смена порта в клиентской части ведь не даст вообще ничего, если серверная часть на удалённом комп-е остаётся настроена на недоступный порт.

Он точно непонимает о чем говорит.
Единственный способ, в случае блокировки порта каким-либо приложением, можно сделать вариант вписывать в серверную часть несколько портов без ограничений на количество.
