### ISSUE TITLE
Пункты меню не совсем логичны

### ISSUE THREAD

**Issue by lzbj77** [dchapyshev/aspia#28]
Сейчас меню Файл и Правка выглядят вот так:

![clipboard03](https://user-images.githubusercontent.com/17875712/42674076-858ef894-8698-11e8-93d8-e8077101d412.jpg)

Гораздо логичнее будет объединить всё что относится к Адресной книге в одно меню.
Назвать его, например, как «Адресная книга» и внутрь поместить все эти пункты:
-	Новая адресная книга
-	Открыть адресную книгу
-	Свойства адресной книги
-	Сохранить адресную книгу
-	Сохранить адресную книгу как…
-	Добавить группу компьютеров
-	Изменить группу компьютеров
-	Удалить группу компьютеров
-	Добавить компьютер
-	Изменить компьютер
-	Удалить компьютер

В меню Файл останется только один пункт – Выход.

**Comment by lumenvindex** [comment]
Не согласен. Не вижу в этом предложении повышения логичности интерфейса. Пользователю достаточно осознать, что основной тип файлов, с которыми работает приложение - адресная книга. И всё тогда становится понятным и логичным.

**Comment by legionpheonix** [comment]
Вы хотите награмождение в интерфейсе, что не есть хорошо.
Меню в данном виде более чем оправдано удобен и прост.
В вашем же случае вы хотите все скомкать в одно, так нельзя делать.

**Comment by dchapyshev** [comment]
Ваша проблема исправлена в версии 1.1.0. Обращение будет закрыто. Если вы считаете, что проблема не исправлена, то можете открыть его снова.
