### ISSUE TITLE
Option for static ID

### ISSUE THREAD

**Issue by izekil** [dchapyshev/aspia#296]
Good day!

Please consider adding an option to make ID "static". I use ASPIA to support my friends and family members, some of them can't see very well or have issues following my instructions what to open and where to look for ID. And if they PC was off for a couple of days ID is prone to change.
Thank you for this amazing software.

**Comment by andreymal** [comment]
> And if they PC was off for a couple of days ID is prone to change.

This should never happen, IDs are persistent and stored in the aspia-router's database. Maybe there is something wrong with your aspia-router installation?

**Comment by izekil** [comment]
> > And if they PC was off for a couple of days ID is prone to change.
> 
> This should never happen, IDs are persistent and stored in the aspia-router's database. Maybe there is something wrong with your aspia-router installation?

Oh I see. Thank you for pointing it out. 
Logs looking normal, I'll check  it in new instance on another VPS
