### ISSUE TITLE
Empty key pool issue

### ISSUE THREAD

**Issue by nickolay3n** [dchapyshev/aspia#302]
доброй ночи, сделал сервер докера, но при подключении к клиентской машине пишет
Нет доступных ретрансляторов или пул ключей пуст.
shared_key_pool.cc:84 takeCredentials] Empty key pool
докер:
version: '3'
services:
central-aspia-server:
image: paprikkafox/aspia-server:latest
container_name: central-aspia-server
hostname: central-aspia-server
environment:
- EXTERNAL_IP=46....
volumes:
- ./data/database:/var/lib/aspia:rw
- ./data/config:/etc/aspia:rw
ports:
- 8070:8070
- 8060:8060
restart: 'always'
————————————————-
cat ./data/config/relay.json
{
"MaxPeerCount": "100",
"PeerAddress": "46....",
"PeerIdleTimeout": "5",
"PeerPort": "8070",
"RouterAddress": "127.0.0.1",
"RouterPort": "8060",
"RouterPublicKey": "1FD2F7C373955F2318BBD1D7CED94B03FFC2E8.....",
"StatisticsEnabled": "false",
"StatisticsInterval": "5"
}
————————————————-
cat ./data/config/router.json
{
"AdminWhiteList": "",
"ClientWhiteList": "",
"HostWhiteList": "",
"Port": "8060",
"PrivateKey": "10319A0610EF1DC3A42109A22A7CC5926C.....",
"RelayWhiteList": "",
"SeedKey": "5C5B59CB56E902...."
}
что то я не так делаю. прошу помощи пожалуйста
PS дубль https://github.com/paprikkafox/aspia-server-docker/issues/3

**Comment by I-Crazy-Demon** [comment]
мой работающий docker-compose.yml
`
version: "3.3"
services:
  aspia-server:
    image: crazydemon/aspia-server:latest
    container_name: central-aspia-server
    hostname: central-aspia-server
    environment:
     - PUID=1000
     - PGID=1000
     - TZ="Asia/Yakutsk"
     - EXTERNAL_IP=9*.*.*.*
    volumes:
     - ./data/database:/var/lib/aspia:rw
     - ./data/config:/etc/aspia:rw
    ports:
      - 8070:8070
      - 8060:8060
    restart: always
`
Разницу вижу лишь в 
`
     - PUID=1000
     - PGID=1000
`
Ну и образ свой собираю.

**Comment by nickolay3n** [comment]
и у меня заработало когда я свой образ сам собрал. тот что на docker hub валяется - в нем не поднимается ретранслятор. как в версии 2.6.5, так и в  2,7,0

**Comment by nickolay3n** [comment]
close
