### ISSUE TITLE
Ошибка инициализации проекта на MacOS 15

### ISSUE THREAD

**Issue by ChaXxl** [dchapyshev/aspia#303]
**Describe the bug**
Ошибка CMake при инициализации

**To Reproduce**
1. `git clone https://github.com/dchapyshev/aspia.git`
2. Клонирование в инженерный каталог: `git clone https://github.com/dchapyshev/vcpkg4aspia.git`
3. Выполнено по каталогу работ: `./vcpkg4aspia/vcpkg install`
4. Qt Creator Работать по документам на официальном сайте. `https://aspia.org/docs/building-macos`
6. See error

**Expected behavior**

**Screenshots**
<img width="1995" alt="image" src="https://github.com/user-attachments/assets/232751d9-854a-4cbf-964e-b9f1b563161c">

**Desktop (please complete the following information):**
 - MacOS 15
 - 2.7.0

**Additional context**

**Comment by ChaXxl** [comment]
Плюс, это нормально.
~~~cmke
find_package(JPEG REQUIRED)
~~~
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/350f159c-a501-4cf0-b76e-9ebfd41937e3">

**Comment by dchapyshev** [comment]
Aspia does not use JPEG. You suggest fighting the consequences, not the cause of the problem. Update vcpkg, I removed the dependency.
