### ISSUE TITLE
Client display error "There are no relays available or the key pool is empty."

### ISSUE THREAD

**Issue by winsoft666** [dchapyshev/aspia#306]
**Screenshots**
<img width="559" alt="ZmaHeBPTTT" src="https://github.com/user-attachments/assets/1554a683-3808-4df6-bac2-28c6927803f8">

**Desktop (please complete the following information):**
 - Windows 10 22H2
 - Aspia version 2.7.0.4866

The following scenarios all report errors:
- Host, Client, Router, Relay run on same machine.
- Host, Router, Relay run on same machine and Client run on another machine.

**Comment by andreymal** [comment]
So do you have a relay? https://aspia.org/docs/relay

**Comment by winsoft666** [comment]
> So do you have a relay? https://aspia.org/docs/relay

yes, I have started relay service at same machine.

**Comment by winsoft666** [comment]
It's my wrong, I didn't configure the relay correctly.
