### ISSUE TITLE
Добавить в ReadMe.MD ссылку на телеграмм-канал

### ISSUE THREAD

**Issue by Diversus23** [dchapyshev/aspia#31]
Вместо
`@aspia_ru`
напишите
`[@aspia_ru](http://t-do.ru/aspia_ru "Telegram channel")`
Тогда по ссылке можно сразу перейти в телеграмм (через t-me.com не работает из-за блокировки, а через t-do.ru работает нормально).
Больше людей на канале - больше идей.
Спасибо.

**Comment by dchapyshev** [comment]
Ссылка добавлена (через https://t.me).

**Comment by Diversus23** [comment]
Дак t.me заблочена, а это альтернатива...
Ну хоть так. Спасибо.

**Comment by dchapyshev** [comment]
t-do.ru показывает рекламу и это сторонний ресурс, который непосредственно к Telegram не относится. https://t.me - открывается у меня (провайдер Дом.ру, Челябинск).

**Comment by Diversus23** [comment]
Во всей РФ не открывается :) Это же ресурс заблокированный Роскомнадзором.
Ну да ладно... Спасибо.

**Comment by dchapyshev** [comment]
У меня открывается :) Средства обхода никто не отменял.
