### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [dchapyshev/aspia#34]
I would like to point out that an identifier like “[`_ASPIA_CLIENT__FILE_REMOVER_H`](https://github.com/dchapyshev/aspia/blob/47b726a93b5046369bf84105d2726eb0f310dcd3/source/client/file_remover.h#L8 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by dchapyshev** [comment]
I know that the names that begin with "_" are reserved.
It would be more correct to use names like ASPIA_CLIENT__FILE_REMOVER_H_ (with symbol "_" at the end).
However, this problem is not critical, but over time it is better to fix it.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by dchapyshev** [comment]
Fixed in [master](https://github.com/dchapyshev/aspia/commit/8e6ba39875440c40877b115dc8586020925ca0b7).

**Comment by elfring** [comment]
There were [some update candidates left over](https://github.com/dchapyshev/aspia/commit/8e6ba39875440c40877b115dc8586020925ca0b7#diff-5507303ac17e948aefe4ca309a8412daR48 "Renaming of include guards"), [weren't there](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Description of the reserved name space")?
