### ISSUE TITLE
Спасибо за качественную программу

### ISSUE THREAD

**Issue by mrkaban** [dchapyshev/aspia#35]
Здравствуйте Дмитрий, спасибо за полезную и качественную программу! Особенно за лицензию!

Программу добавил на мой сайт о свободном программном обеспечении ([ссылка](https://континентсвободы.рф/утилиты/прочее/aspia-удаленное-управление-компьютером.html)).

Хочется немного больше интекрактивности для настроек сервера, через программу не посмотришь, запущен он или нет, и как отключить на время. 

Также было бы немного иметь возможность отправлять и запускать файл. Например, сделал скрипт изменения сервера WSUS и отправил всем клиентам.

Ну и естественно акцент на массовое управление будет в будущем?

Искренне желаю активного развития программы Aspia.

Кстати, такое название уже есть у программы для отображения информации о компьютере ([ссылка](https://континентсвободы.рф/утилиты/система/aspia-программа-сбора-информации-о-компьютере.html)). Не связана ли она с Вами?

**Comment by dchapyshev** [comment]
Здравствуйте!
Управление службой было бы неплохо добавить в конфигуратор, согласен.
На счет массового управления пока не думал, но в будущем - может быть.

Программа по вашей ссылке - это так же моя программа, но ее развитие уже остановлено. Весь функционал будет перенесен в текущую программу (будет возможно то же самое, но по сети).

**Comment by mrkaban** [comment]
Интересно! Будем ждать будущих релизов!

Также, пользуясь случаем, хочу поблагодарить за программу для отображения информации о компьютере, на мой личный взгляд она лучшая среди свободный.

**Comment by mrkaban** [comment]
Я являюсь фанатом Veyon, но она для управления компьютерным классом, и желая помочь, приведу некоторые особенности с целью рассмотрения возможности потенциального добавления в будущем:

демонстрация экрана конкретному компьютеру, а также всему классу (оконная и полноэкранная);
поддержка протокола LDAP/AD;
мониторинг и дистанционное управление всеми компьютерами;
создание скриншотов;
возможность заблокировать конкретный компьютер или весь класс;
отправка текстовых сообщений;
включение/выключение и перезагрузка удаленных компьютеров;
удаленный выход из системы и удаленное выполнение произвольных команд/скриптов;
открытие веб-сайта на удаленном компьютере.

Тикет можно закрыть.
