### ISSUE TITLE
CMake не создаёт aspia.sln, не компилирует и выкидывает ошибку

### ISSUE THREAD

**Issue by Shultc** [dchapyshev/aspia#37]
При попытке создать aspia.sln по инструкции из [BUILDING.md](https://github.com/dchapyshev/aspia/blob/master/BUILDING.md) на 7-ом шагу вылетает ошибка:
```
C:\...\NotMy\aspia-master\build>cmake ..\source -G "Visual Studio 15 2017"
CMake Error at CMakeLists.txt:15 (project):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "C:/../NotMy/aspia-master/build/CMakeFiles/CMakeOutput.log".
```
Через CMake GUI тоже ошибка `Configuring incomplete, errors occurred!`

Всё содержимое файла CMakeOutput.log:
`The system is: Windows - 7.0 - AMD64
`

**Comment by dchapyshev** [comment]
CMake не может найти установленную Visual Studio 2017. Либо она не установлена, либо установлена криво.
Автоматическая сборка проводится на AppVeyor после каждого коммита, никаких проблем со сборкой нет.

**Comment by Shultc** [comment]
Большое спасибо!
Этот лог-файл сбил с толку.
Теперь всё работает!
