### ISSUE TITLE
После обновления удалился пользователь

### ISSUE THREAD

**Issue by 3-50** [dchapyshev/aspia#38]
После обновления на 1.0.1 пришлось заново добавлять пользователей сервера. Обновлял подключенным через Aspia. Windows 7, x64. После того как обновление закончилось, попытка подключиться не удалась. Подключившись через TeamViewer, увидел, что пользователей сервера нет.

Или так и задумано?

**Comment by dchapyshev** [comment]
Это одна из проблем, которая была исправлена в 1.0.1. Теперь параметры не удаляются при удалении приложения.
Хотя, правильнее сделать возможность выбора: удалять или не удалять параметры при удалении приложения.
При обновлении с 1.0.0 на 1.0.1 лучше сделать копию ветки реестра (HKLM\Software\Aspia) и после обновления импортировать ее обратно.

**Comment by CHERTS** [comment]
Удаление - это одна операция. Обновление - это другая операция.
Если пользователь обновляет программу, то логично настройки не удалять. Нужно предусмотреть соответствующие проверки в инсталляторе.
Если программу удаляют совсем, то и настройки должны полностью удаляться, зачем оставлять после себя мусор в реестре.
