### ISSUE TITLE
Действие кнопки Отмена при закрытии программы и опечатки.

### ISSUE THREAD

**Issue by 3-50** [dchapyshev/aspia#39]
1.
Внесли изменения в компьютер, записанный в адресную книгу, при выходе из программы будет предложено сохранить изменения, не сохранять и отменить. По идее отмена должна отменить процесс закрытия, но нет.
2.
При редактировании пароля в настройке сервера "щелчек" заменить на "щелчок".

При удалении группы компьютеров в адресной книге "дочернии" заменить на "дочерние".

**Comment by dchapyshev** [comment]
Спасибо за отчет о найденных ошибках!
Всё перечисленное исправлено в master.

**Comment by 3-50** [comment]
"Не удалось создать директорию: Доступ запр_о_щен" на "Не удалось создать директорию: доступ запр_е_щен".

**Comment by dchapyshev** [comment]
Исправлено.

**Comment by 3-50** [comment]
Еще немного опечаток
В фразе "Слишком длинный *коментарий*. Максимальная *длинна коментария* 2048 символов. "
заменить на "комментарий, длина, комментария".
В свойствах адресной книги, группе компьютеров и компьютере заменить *Коментарий:* на "Комментарий:".

В фразах "При изменении количества итераций хеширования вам *прийдется* ввести пароль заново" и "При изменении размера соли для хеширования вам *прийдется* ввести пароль заново."
заменить на "придется".
В фразе "Не удалось *запусить* службу." заменить на "запустить".
