### ISSUE TITLE
Не взаимодействует с Kaspersky Free на удаленном компьютере

### ISSUE THREAD

**Issue by 3-50** [dchapyshev/aspia#40]
На удаленном компьютере установлен Kaspersky Free, версии 16.01.445, 18.0.0.405.

TeamViewer позволяет с ним работать, а Aspia нет, вообще реакции никакой нет при попытке нажать хоть на что-то, только реакция на правую кнопку мыши на иконке в трее.

**Comment by dchapyshev** [comment]
Для внедрения ввода используется функция SendInput. Данная функция не может внедрять ввод в процессы, которые имеют более высокий уровень целостности (integrity level). Однако, Aspia имеет уровень целостности выше, чем UI антивируса Касперского. Так же для внедрения ввода процесс приложения должен иметь атрибут UI-access и он так же имеется.
Я сходу не вижу документированных препятствий, которые мешали бы осуществлять ввод, однако он не работает. По всей видимости, UI антивируса Касперского устанавливает какие-то атрибуты безопасности для своего окна. Пока я не придумал, как это обойти.

**Comment by unwo** [comment]
Незнаю как во free версии касперского, а в kaspersky endpoint security есть раздел доверенная зона, доверенные программы. Для добавляемых программ доступен параметр: Не блокировать взаимодействие с интерфейсом программы. Возможно это более легальный способ взаимодействия с касперским, чтобы он не стал считать aspia вредной программой.

**Comment by dchapyshev** [comment]
Может быть TeamViewer потому и работает с интерфейсом антивируса, что имеется в доверенных приложениях (изначально, а не добавлен пользователем).

**Comment by 3-50** [comment]
Да, в Kaspersky Free есть аналогичные параметры.
