### ISSUE TITLE
При смене языка вместо значений клавиш отправляются сочетания клавиш

### ISSUE THREAD

**Issue by 3-50** [dchapyshev/aspia#41]
При смене языковой раскладки в некоторых случаях начинает транслироваться с клиента на сервер не нажатия на кнопки, а сочетания. Например, подключаюсь к серверу, выбираю файл на рабочем столе, жму на f2, пишу на клиентской машине "zxc", на сервера появляется меню, соответствующее сочетанию клавиш "win+x", если нажму на "r",  то это будет соответствовать сочетанию "win+r".
Пока не могу восстановить точную последовательность действий, но ощущение, что связано с переключением языков. Дополню, если выясню.
Windows 10 - Windows 10

**Comment by dchapyshev** [comment]
По сети передаются коды клавиш клавиатуры, они не зависят от языка. Непосредственно с переключением раскладки это не может быть связано.
Скорее всего проблема с тем, что на удаленный компьютер была отправлена команда нажатия кнопки, а команда отпустить ее не была отправлена :)
Буду разбираться.

**Comment by 3-50** [comment]
Установил закономерность.
Клиент: Английский; Cервер: Английский 
Клиент: win+space (альтернативное переключение языка с Windows 7 что ли)
Клиент: Русский; Cервер: Английский 
Выбираем любой файл на сервере, жмём на f2, пишем "ert", на сервер отправляется сочетание клавиш "win+e", "win+r".
Жмем кнопку "Windows", появляется меню Пуск на клиенте, затем на сервере, выбираем любой файл на сервере, жмём на f2, пишем "ert", файл переименовывается на "ert".

**Comment by dchapyshev** [comment]
Я сделал отпускание всех нажатых кнопок клавиатуры при потере окном фокуса ввода.
Попробуйте потестировать версию из master. Скачать собранные файлы можно [тут](https://aspia.org/files/master.7z) (файлы подписаны электронной подписью). Просто замените существующие файлы программы, на те, которые в архиве.

**Comment by 3-50** [comment]
Хорошо, а то я как раз пытаюсь осуществить вышеописанное, и как-то не очень получается. Простая замена по факту ничего не дает, наоборот ошибки появляются, варианты с "--remove-service", тоже ни к чему не привели, а до других вариантов еще не успел добраться.

**Comment by dchapyshev** [comment]
Проблема отлично воспроизводится: просто нажимаем Win+Space. Нажатие Win ловится отлично, а при нажатии Space Windows перехватывает комбинацию и приложение не получает уведомления о том, что кнопка отпущена. Соответственно, кнопка Win остается в нажатом состоянии и никак узнать о том, что она была отпущена мы не можем.
Единственное решение, которое мне приходит в голову - это установка хука клавиатуры, т.е. перехват всех нажатий кнопок пока приложение имеет фокус ввода и снятие хука, когда фокус переводится в другое окно.
Попробую реализовать, отпишусь.

**Comment by dchapyshev** [comment]
Сделал перехват всех системных комбинаций (которые возможно сделать). Теперь весь ввод при активном окне отправляется в удаленный компьютер, включая Win, Win+Space, Alt+Tab и т.д.
Просьба протестировать, ссылка [прежняя](https://aspia.org/files/master.7z).

**Comment by 3-50** [comment]
На первый взгляд отрабатывает как и должно. Спасибо.
Раз уж тут обсуждаем проблему с сочетанием клавиш, то добавлю следующий момент: 
Подключился к серверу, хочу отправить произвольное сочетание клавиш (ctrl+shift+esc), что в релизных версиях не отлавливал сочетания, что в этой. Баг?
И кажется на еще один наткнулся, сейчас осмыслю, что произошло и в чем дело может быть.

Можно, пожалуйста, версии мастера каким-либо образом выделять? Например, 1.0.1.3?

**Comment by 3-50** [comment]
Ок, вам не сложно, при возможности, добавить следующие сочетания:
win+r
ctrl-shift-esc
?

Первый вариант, кажется, более userfriendly.

С одной стороны да, а с другой для бета тестеров это лишнее подтверждение, что обновилось всё корректно и на нужную версию.

**Comment by 3-50** [comment]
На 1.0.1 обнаружил, что простое нажатие на клиенте (Windows 10 x64) на английскую букву P соответствует сочетанию клавиш Win-P на сервере (Windows 7 x64).

**Comment by dchapyshev** [comment]
Это исправлено после 1.0.1, соответственно, проверять в 1.0.1 не имеет смысла.
