### ISSUE TITLE
Add setting for remote computer to allow connection.

### ISSUE THREAD

**Issue by SirJosh3917** [dchapyshev/aspia#47]
Hello! Could you make a setting where the remote computer must first allow the other computer to connect? Thank you!

An example, drawn badly in Paint.NET, is shown here:

[Example](https://upl.sirjosh3917.com/DroopyVelvetworm.png "Example")

**Comment by dchapyshev** [comment]
It is a bad idea. Users often click the buttons and do not think where to click. Thus, the user can accidentally click the "Allow" button. An attacker can take advantage of this.

**Comment by SirJosh3917** [comment]
https://upl.sirjosh3917.com/BasicOrangutan.png
Similar to how there's "Desktop Manage", "Desktop View", and "File Transfer", I believe there should be a similar mode like "Request Connection". You'd first have to have the correct username and password, and then it would ask the other computer if it could connect.

An example usage of this is me and my brother, if I want to watch him play video games, I could remote connect into his computer ( with the Request Connection mode ) and watch him play. Does this make the request clearer?

**Comment by legionpheonix** [comment]
Кстати очень хорошее предложение в корпоративе.
Сколько не встречал случаев, пользователь боиться слежки.
Надо сделать режим без и с запросом на подключение.
Скажем так это этика и было бы приятно пользователю видеть кто к нему подключается и когда.

**Comment by Worgang** [comment]
> It is a bad idea. Users often click the buttons and do not think where to click. Thus, the user can accidentally click the "Allow" button. An attacker can take advantage of this.

Дмитрий Вы скорее всего его не поняли. Пароль и Логин создаваться будет, все остается как есть. Просто в настройках конфигурации сервера появится галочка "Предоставлять доступ только после подтверждения". А у пользователя будет появляться окошко разрешить доступ к компьютеру для пользователя Admin. Я активно использую Вашу программу у себя на работе. Просто есть люди, которые не хотят чтобы к ним подключались в тот момент когда они работают. А также для создания защиты от несанкционированного доступа. К примеру на ПК находятся конфиденциальная информация и пользователь хочет контролировать работу удаленного специалиста. Наблюдая за его действиями.

**Comment by r57zone** [comment]
Или просто настройку на сервере хосте, чтобы была возможность ввести разрешенные IP адреса, как в Radmin.

**Comment by alexey-gamov** [comment]
Думаю можно закрыть данный запрос. Реализовано.

**Comment by dchapyshev** [comment]
Implemented in 2.2.0 version.

**Comment by r57zone** [comment]
Couldn't find it in the settings 😟

**Comment by dchapyshev** [comment]
Settings -> Security -> Connection Confirmation
