### ISSUE TITLE
Feature Request: Cycle through monitors

### ISSUE THREAD

**Issue by Memphizzz** [dchapyshev/aspia#48]
Hi,

first of all, thank you for the great work you've put into aspia! It's a brilliant peace of software!
As I'm working with multiple monitors, i wanted to ask if you could implement a button to cycle through monitors instead of having all of them next to each other.

Thank you and keep up the great work,

MemphiZ

**Comment by dchapyshev** [comment]
Hi,
The monitor selection function has already been implemented (in master). You can test the development version: https://aspia.org/files/master.7z

**Comment by Memphizzz** [comment]
Hi,

I've just tested it and it works but unfortunately only one way. I have a friend who has 2 monitors, to whom i can connect fine. But if he tries to connect to me with my tree monitors, he gets the following error:

18:59:14 Attempt to connect to localhost:44441.
18:59:14 Connection established.
18:59:14 Session started.
18:59:16 Session error: Wrong video frame position.
18:59:16 Disconnected.

We're routing the connection through an SSH port forwarding tunnel thats why its a local port.
This worked before we patched our installations with the master.7z.

I didn't change anything, the only obvious difference I see between mine and his setup is that i have 3 instead of 2.

Any Ideas what this might be?

**Comment by dchapyshev** [comment]
You need to update the server side and the client side (both). The new version will be incompatible with the old.

**Comment by Memphizzz** [comment]
I thought so and I did. I will verify using the released version tomorrow and report back.

**Comment by Memphizzz** [comment]
Sorry, for the delay but I've tried it now. I even used a third computer to verify. I did the following:
I install the released 1.0.1 version. Stop the service and replace all files in Program Files (x86)\Aspia with the ones from the master.zip. Start the service.

When I connect from a client using the released aspia console, I get: 
```
19:39:19 Attempt to connect to <HOSTNAME>:22.
19:39:19 Network error: The remote host closed the connection.
19:39:19 Disconnected.
```
as expected.
But with the new console, it starts connecting, a little black screen is shown for a sec and then it exits with:
```
19:40:27 Attempt to connect to <HOSTNAME>:22.
19:40:28 Connection established.
19:40:28 Session started.
19:40:29 Session error: Wrong video frame position.
19:40:29 Disconnected.
```

This is over VPN on a custom port as you can see. As of right now, I reverted everything back to 1.0.1.

Any Ideas?

**Comment by dchapyshev** [comment]
I need to know the location of the monitors and of the dimensions (resolution) on each of them.
Something like this: [https://ibb.co/iNcC3e](https://ibb.co/iNcC3e).
I also need to know the version of the operating system.

**Comment by Memphizzz** [comment]
Sure, no problem:

![left](https://user-images.githubusercontent.com/4660924/46551906-4ff95980-c8d9-11e8-8eb4-37ec4d9a7a9b.JPG)
![main](https://user-images.githubusercontent.com/4660924/46551907-4ff95980-c8d9-11e8-8a5e-c4681b1a2c2a.JPG)
![right](https://user-images.githubusercontent.com/4660924/46551908-4ff95980-c8d9-11e8-9a94-fa98a9fca961.JPG)

Windows:
Edition: 10 Pro
Version: 1803
Build: 17134.286

This is one of the computers, the other one where I get the same error has almost the same setup, also 3 monitors aligned like that, just the resolutions differ.

**Comment by dchapyshev** [comment]
I managed to repeat your problem. I will try to fix it soon. I'll let you know when the results will be.

**Comment by Memphizzz** [comment]
Awesome, thank you very much! I'm looking forward to it!

**Comment by dchapyshev** [comment]
I fixed some bugs. [File](https://aspia.org/files/master.7x) has been updated. You must upgrade the client and server.
Is the problem fixed?

**Comment by Memphizzz** [comment]
It works like a charm! Thanks again!
