### ISSUE TITLE
Не удаляется не переданный файл

### ISSUE THREAD

**Issue by alec1490** [dchapyshev/aspia#49]
При прерывании передачи файла и попытки удаления его, файл занят процессом aspia_console.exe

**Comment by dchapyshev** [comment]
Проблема известная, в master она исправлена (но не до конца, при закрытии диалога копирования через кнопку закрытия окна файл по прежнему не удаляется).

**Comment by dchapyshev** [comment]
Ваша проблема исправлена в версии 1.1.0. Обращение будет закрыто. Если вы считаете, что проблема не исправлена, то можете открыть его снова.
