### ISSUE TITLE
Боковая панель уведомления о текущем соединении

### ISSUE THREAD

**Issue by poweruserq** [dchapyshev/aspia#50]
Приветсвую!

Хочу выразить благодарность за проделанную работу и отличный продукт!

Вопрос: Есть ли способ спрятать/отключить отображение панели уведомления о текущем соединении? Это та панель что появляеться на клиентской стороне, в правой нижней части экрана.

Заранее благодарю..

![tab](https://user-images.githubusercontent.com/44506490/47581731-f8d82900-d95a-11e8-9551-8844a878df33.jpg)

**Comment by dchapyshev** [comment]
Здравствуйте!
Процитирую ответ на данный вопрос из FAQ на форуме:

> Нет. Пользователь должен быть явно уведомлен о наличии удаленного подключения. Наличие возможности отключить уведомления при этом приравнивается к отсутствию уведомлений.
Данные требования диктуются антивирусными компаниями. Для того, чтобы программа была в белых списках антивирусов, необходимо выполнения ряда условий и уведомление пользователя является обязательным.
