### ISSUE TITLE
Пожалуйста распишите сборку по подробнее, может быть у вас есть скрипт для сборки ?

### ISSUE THREAD

**Issue by freexmonster** [dchapyshev/aspia#6]
пожалуйста распишите сборку по подробнее, может быть у вас есть скрипт для сборки ?

**Comment by dchapyshev** [comment]
Сборку какого бранча вы имеете ввиду? qt_rewrite или master?
Инструкция по сборка master в BUILDING.md.
qt_rewrite на данный момент сложно собрать самостоятельно. Вам прийдется самостоятельно собрать qt, openssl, protobuf, libvpx, libyuv. Я еще не завершил переписывание, после завершения будет подготовлен пакет с собранными сторонними библиотеками.
Вы можете скачать собранную версию тут: https://aspia.ru/files/aspia.7z

**Comment by dchapyshev** [comment]
Бранч qt-rewrite перемещен в master. Добавлена инструкция по сборке (файл BUILDING.md).
