### ISSUE TITLE
ASPIA_THIRD_PARTY_DIR configuration

### ISSUE THREAD

**Issue by lostStara** [dchapyshev/aspia#67]
Can you provide an example?
                                      Thank you very much

**Comment by egorpugin** [comment]
You could try to build with sw if you want to build aspia.
https://github.com/dchapyshev/aspia/blob/master/doc/building.md#alternative-instructions-sw-build-system

**Comment by lostStara** [comment]
Thank you very much

**Comment by dchapyshev** [comment]
Your bug report should match one of the templates that are offered during creation (Bug report, Feature request).
Now your reports do not contain any useful information.
The issue will be closed. Create a new issue in accordance with the rules of the project.
