### ISSUE TITLE
Remote host closed the connection.

### ISSUE THREAD

**Issue by lostStara** [dchapyshev/aspia#68]
10:34:50 Attempt to connect to 192.168.1.206:8050.
10:34:51 Session started.
10:35:05 Remote host closed the connection.

**Comment by dchapyshev** [comment]
Your bug report should match one of the templates that are offered during creation (Bug report, Feature request).
Now your reports do not contain any useful information.
The issue will be closed. Create a new issue in accordance with the rules of the project.
