### ISSUE TITLE
c#

### ISSUE THREAD

**Issue by jigneshBadrakhiya** [dchapyshev/aspia#7]
can u implement in c#

**Comment by dchapyshev** [comment]
The project is completely written using the library Qt. The implementation on C# portends a complete rewriting of the entire code of the program. This will require a very large amount of effort. I'm the only developer of the program and I do not have that much time. Unfortunately, this does not make any sense.

**Comment by jigneshBadrakhiya** [comment]
thanks

**Comment by lostStara** [comment]
Hi
Can it be encapsulated as a DLL for C# calls

**Comment by lostStara** [comment]
I want to parse the data format and call c#，Is the idea ok?

**Comment by jigneshBadrakhiya** [comment]
yes
