### ISSUE TITLE
Translation - Portuguese Brazilian

### ISSUE THREAD

**Issue by hebertn88** [dchapyshev/aspia#70]
Hi, I am a Brazilian user and would like to help with the translation into my Language (Portuguese Brazilian). Could you help me with how to do it?

**Comment by dchapyshev** [comment]
Hi.
Is Portuguese in Brazil something different from Portuguese in Portugal?

The following language codes exist:
pt - Portuguese
pt-BR - Portuguese (Brazil)
pt-PT - Portuguese (Portugal)

Does it make sense to make a separate template for pt-BR or can I make pt?

**Comment by hebertn88** [comment]
Yes, there are differences. The ideal is to separate. I am not able to do the translation from Portugal.

Unless we understand it better we leave only 'pt' while we do not find anyone willing to do the work of Portugal. Despite the difference, a person from portugal would understand much of the Brazilian Portuguese

**Comment by dchapyshev** [comment]
Templates for translation are ready. You can complete the translation by following the [instructions](https://github.com/dchapyshev/aspia/blob/master/doc/translators.md).

**Comment by hebertn88** [comment]
Thanks man

**Comment by hebertn88** [comment]
Hi, sorry for the delay! But I finally managed to complete the translation!
I would like to congratulate everyone involved in the app development! Great job! I have been using Aspia in my daily work...

I created a [fork](https://github.com/hebertn88/aspia) on my github with the translation I made.

**Comment by egorpugin** [comment]
Please open a pull request with your changes.

**Comment by hebertn88** [comment]
I have created [pull request](https://github.com/dchapyshev/aspia/pull/123)
