### ISSUE TITLE
how to bulid thitd party lib？

### ISSUE THREAD

**Issue by 844655441** [dchapyshev/aspia#81]
i bulided the aspia sln for win32 release version in vs2019，but tips that the third party lib is old version, so how to get the 3-rd lib source and how to rebulid？

**Comment by egorpugin** [comment]
You could try to use sw build (see build instructions).
It will build fresh deps, but in specific way.

**Comment by blockspacer** [comment]
What do you think about conan.io ?

I noticed that project uses `base` library from chromium, you can find conan package for it here https://github.com/blockspacer/chromium_base_conan (usage example https://github.com/blockspacer/flextool)

**Comment by Aldebaran2012** [comment]
@844655441 or someone else excuse me, do you can share me the way that you builded the aspia sln please? I am working on it, ni advanded thanks a lot guys.

**Comment by dchapyshev** [comment]
In newer versions, third-party libraries are built in vcpkg.
