### ISSUE TITLE
C++ compiler optimization leads to ACCESS_VIOLATION

### ISSUE THREAD

**Issue by andrew-boyarshin** [dchapyshev/aspia#83]
<https://github.com/dchapyshev/aspia/blob/cdfe1ff57ff75951c14dfd17f0ee5246de3db4b7/source/host/user_session_manager.cc#L303>
cppreference: [order of evaluation, rule 15](https://en.cppreference.com/w/cpp/language/eval_order)

MSVC 14.26.28619 (and at least 14.25 does that too) actually swaps these two arguments. Guess where `this` is `nullptr`. :)

By the way, the behavior is exhibited even in Debug mode.

The fix is simple: do not rely on the evaluation order of arguments.

**Comment by dchapyshev** [comment]
Fixed in ada87f49668e00cfca782ccfa918076fe30d9808.
