### ISSUE TITLE
Закрывается окно консоли

### ISSUE THREAD

**Issue by Urvdmih** [dchapyshev/aspia#85]
Включена настройка "Сворачивать в трей".
Запускаю подключение, консоль сворачиваю в трей.
Если закрываю подключение - программа (консоль в трее) тоже закрывается. 
При если перед закрытием подключения развернуть консоль из трея - то она не закрывается.

Aspia 1.1.2
Windows 7 x 64 SP1 Pro

**Comment by dchapyshev** [comment]
Исправлено в 4ea135bed1fcd4c9f923a3f5abef8b3e4919e0ca.
