### ISSUE TITLE
Translation-Simplified Chinese

### ISSUE THREAD

**Issue by dnybz** [dchapyshev/aspia#92]
Hi, I am a China user, I hope to be able to add simplified Chinese, thank you!

**Comment by dchapyshev** [comment]
Hi.
You can use the instructions to translate the application into your language: https://github.com/dchapyshev/aspia/blob/master/doc/translators.md

**Comment by dnybz** [comment]
Hi.

The attachment is the simplified Chinese translation file I submitted. I hope you can add it to the program, thank you!

[translations_zh_CN.zip](https://github.com/dchapyshev/aspia/files/5274917/translations_zh_CN.zip)
