### ISSUE TITLE
[feature] демон-посредник для установки на свой VPS (а-ля teamviewer/anydesk)

### ISSUE THREAD

**Issue by msva** [dchapyshev/aspia#98]
Было бы неплохо так же добавить поддержку работы с таким демоном-посредником в клиент и сервер (и запилить таковой демон сам по себе), который бы помогал обеспечить связь между клиентом и сервером, когда оба за натом.

У "конкурентов" для этого придуманы "тикеты" на основе цифрового ID.
Думаю, можно сделать что-нибудь подобное (можно даже не привязываться к цифрам, а позволять юзерам самим именовать свои девайсы и регистрировать "сервер" на посреднике под этим именем).

**Comment by AlonsoMackenlly** [comment]
Поддерживаю, единственный годный репо для этих целей

**Comment by ros-tel** [comment]
Готов взяться за написание серверной части, но нужен кто-то кто возьмется за реализацию протокола в aspia.
Некоторый опыт в реализации подобных вещей имеется.

Для связи https://t.me/rostel

**Comment by ros-tel** [comment]
Набросал схемку использования простого сервера управляющих соединений.
![Сервер управляющих соединений drawio](https://user-images.githubusercontent.com/7720609/145776411-d8c23820-a80d-41c8-b996-5efada4330a5.png)

**Comment by ros-tel** [comment]
В продолжение предыдущей схемы.
Позволяет почти масштабировать нагрузку на сервера управляющих соединений.

![С балансированием нагрузки drawio](https://user-images.githubusercontent.com/7720609/145783529-1a4741d8-3132-4b6c-99ff-55d60cbd3b17.png)

**Comment by dchapyshev** [comment]
Это уже год как реализовано (обход NAT через сервер-посредник). Смотрите "aspia-router" и "aspia-relay" на странице релизов. Имеются версии для Linux/Windows.

**Comment by dchapyshev** [comment]
Implemented in 2.0.0 version.
